<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MechJeb2</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Assembly-CSharp" />
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="JetBrains.Annotations" />
    <Reference Include="UnityEngine.IMGUIModule" />
    <Reference Include="UnityEngine.PhysicsModule" />
    <Reference Include="MechJebLib" />
    <Reference Include="UnityEngine.AssetBundleModule" />
    <Reference Include="MechJebLibBindings" />
    <Reference Include="alglib" />
    <Reference Include="System.Core" />
    <Reference Include="UnityEngine.AnimationModule" />
    <Reference Include="UnityEngine.TextRenderingModule" />
    <Reference Include="UnityEngine.InputLegacyModule" />
    <Reference Include="UnityEngine.UI" />
    <Reference Include="Assembly-CSharp-firstpass" />
  </ItemGroup>
</Project>